(function(){for(var a=0,b=["ms","moz","webkit","o"],c=0;c<b.length&&!window.requestAnimationFrame;++c){window.requestAnimationFrame=window[b[c]+"RequestAnimationFrame"];window.cancelAnimationFrame=window[b[c]+"CancelAnimationFrame"]||window[b[c]+"CancelRequestAnimationFrame"]}if(!window.requestAnimationFrame)window.requestAnimationFrame=function(d){var e=(new Date).getTime(),g=Math.max(0,16-(e-a)),j=window.setTimeout(function(){d(e+g)},g);a=e+g;return j};if(!window.cancelAnimationFrame)window.cancelAnimationFrame=
function(d){clearTimeout(d)}})();if(!window.getComputedStyle)window.getComputedStyle=function(a){this.el=a;this.getPropertyValue=function(b){var c=/(\-([a-z]){1})/g;if(b=="float")b="styleFloat";if(c.test(b))b=b.replace(c,function(d,e,g){return g.toUpperCase()});return a.currentStyle[b]?a.currentStyle[b]:null};return this};
EKTweener=function(a,b){function c(f){return typeof HTMLElement==="object"?f instanceof HTMLElement:typeof f==="object"&&f.nodeType===1&&typeof f.nodeName==="string"}function d(){for(var f=a.createElement("div"),h="Webkit Moz O ms".split(" "),i=h.length;i--;)if(h[i]+"Transform"in f.style){u=h[i];break}}function e(f){if(o[f])f=o[f];for(var h=0;h<q.length;h++)if(q[h]===f)return u+f.charAt(0).toUpperCase()+f.slice(1);return f}function g(f){for(var h in f){var i=h;if(o[h])i=o[h];for(var k=0;k<q.length;k++)if(q[k]===
i){i=u+i.charAt(0).toUpperCase()+i.slice(1);break}if(h!==i){f[i]=f[h];delete f[h]}}}function j(f){g(f);g(f.plugin)}function B(f,h){if(!h.plugin)h.plugin={};if(!h.suffix)h.suffix={};for(property in h){if(v[property]&&!h.plugin[property])h.plugin[property]=v[property];if(w[property]&&!h.suffix[property])h.suffix[property]=w[property]}j(h)}function x(f,h,i,k){if(f.jquery){var l=[];f.each(function(){l[l.length]=x(this,h,i,k)});return l.length>1?l:l[0]}var n;if(c(f)&&i.skipHTMLParsing!=true){n=f.style;
B(f,i)}else{n=f;i.appliedTarget=f}if(typeof f.tweenId==="undefined"){f.tweenId=r.length;r[f.tweenId]=[]}var t=i.delay==C?0:i.delay;delete i.delay;n=new EKTween(f,n,h,t,i,k||false);r[f.tweenId].push(n);k||n.onLoop();return n}function y(f,h,i,k){if(f.jquery){var l=[];f.each(function(){l[l.length]=y(this,h,i,k)});return l.length>1?l:l[0]}var n=x(f,h,k,true);c(f)&&k.skipHTMLParsing!=true&&j(i);for(var t in i)n.changeFrom(t,i[t]);n.onLoop();return n}function z(f){if(f.jquery)f.each(function(){z(this)});
else if(f=r[f.tweenId]){for(;f[0];){f[0].removeProperties();f[0].kill();delete f[0]}f.splice(0,f.length)}}function A(f){return r[f.tweenId]}function D(f,h){if(o[h])h=o[h];f=A(f);if(!f)return null;for(var i=f.length;i--;)if(f[i].properties[h])return f[i];return null}function E(f,h){f=propertyName=e(f);var i=/[A-Z]/g;if(propertyName.search(i)>-1){f=propertyName.replace(i,function(l){return"-"+l.toLowerCase()});if(f.indexOf("ms")==0)f="-"+f}if(a.body){if(!s){s=a.createElement("div");p=s.style;p.position=
"absolute";p.top=p.left="-9000px";document.body.appendChild(s)}p[propertyName]=h;return b.getComputedStyle(s,"null").getPropertyValue(f)}i=a.createElement("body");var k=a.createElement("div");a.documentElement.appendChild(i);i.appendChild(k);p[propertyName]=h;h=b.getComputedStyle(k,"null").getPropertyValue(f);a.documentElement.removeChild(i);k=i=null;return h}var C,m={},u="",s,p,v={},q=[],o={},w={width:"px",height:"px",top:"px",left:"px",bottom:"px",right:"px",marginTop:"px",marginLeft:"px",marginBottom:"px",
marginRight:"px",paddingTop:"px",paddingLeft:"px",paddingBottom:"px",paddingRight:"px",fontSize:"px",size:"px"},r=[];d();m.HTMLPlugins=v;m.HTMLSuffix=w;m.HTMLPrefixedStyle=q;m.HTMLStyleAlias=o;m.getPropertyName=e;m.getStyle=E;m.to=x;m.fromTo=y;m.killTweensOf=z;m.getTweens=A;m.getTween=D;return m}(document,window);
function EKTween(a,b,c,d,e,g){this._target=a;this._appliedTarget=b;this._isStyle=a!==b;this._data=e;this._pauseTime=0;this._isStarted=this._isPaused=false;this._currentTime=(new Date).getTime();this._startTime=d*1E3+this._currentTime;this._durationTime=(c||0)*1E3;this._hasFrom=g;this.isFinished=false;this.ease=EKTweenFunc.defaultFunc;this.onCompleteParams=this.onComplete=this.onUpdateParams=this.onUpdate=this.onStartParams=this.onStart=this.tweens=null;this.properties={};this.prefix={};this.suffix=
{};this.yoyo={};this.plugin={};this.init()}
EKTween.prototype={init:function(){function a(c,d){return function(){return c.apply(d,Array.prototype.slice.call(arguments))}}for(var b in this._data.plugin)this.plugin[b]=new this._data.plugin[b];for(b in this._data)switch(b){case "ease":this.ease=EKTweenFunc[this._data[b]];break;case "prefix":case "suffix":case "yoyo":case "onStart":case "onStartParams":case "onUpdate":case "onUpdateParams":case "onComplete":case "onCompleteParams":this[b]=this._data[b];break;case "plugin":break;default:this.properties[b]=
[this.plugin[b]?1:this._data[b],0];this.plugin[b]&&this.plugin[b].setTo(this._data[b],this._appliedTarget)}if(this.yoyo&&this._isStyle)for(b=0;b<this.yoyo.length;b++)this.yoyo[b]=EKTweener.getPropertyName(this.yoyo[b]);if(this.tweens=EKTweener.getTweens(this._target))if(this.tweens.length>0)for(b=this.tweens.length;b--;)if(this.tweens[b].removeProperties(this.properties)==0){this.tweens[b].kill();this.tweens.splice(b,1)}delete this._data;this.onLoop=a(this.onLoop,this)},update:function(){if(this.onUpdate)this.onUpdateParams?
this.onUpdate.apply(this,this.onUpdateParams):this.onUpdate()},onLoop:function(){if(!this.isFinished){requestAnimationFrame(this.onLoop);this._currentTime=(new Date).getTime();this._isPaused||this.render()}},render:function(){if(this._currentTime>=this._startTime){if(!this._isStarted){if(!this._hasFrom)for(var a in this.properties)this.setProperty(a,this.properties[a]);if(this.onStart)this.onStartParams?this.onStart.apply(this,this.onStartParams):this.onStart();this._isStarted=true}if(this._currentTime>=
this._durationTime+this._startTime){for(a in this.properties)this.setValue(this.properties[a][4]?this.properties[a][1]:this.properties[a][0],a,this.properties[a]);this.update();if(this.onComplete)this.onCompleteParams?this.onComplete.apply(this,this.onCompleteParams):this.onComplete();this.kill();for(a=this.tweens.length;a--;)this.tweens[a]&&this.tweens[a].isFinished&&this.tweens.splice(a,1)}else{for(a in this.properties)this.setEaseValue(a,this.properties[a]);this.update()}}},setProperty:function(a,
b){var c;if(this.prefix)if(this.prefix[a])b[2]=this.prefix[a];if(this.suffix)if(this.suffix[a])b[3]=this.suffix[a];if(this.yoyo)for(c=0;c<this.yoyo.length;c++)if(this.yoyo[c]===a){b[4]=true;break}if(this._isStyle){c=this.getCurrentPropertyValue(a);if(this.plugin[a]){this.plugin[a].setFrom(c);b[1]=0}else b[1]=parseFloat(c)}else b[1]=parseFloat(this._appliedTarget[a]);if(isNaN(b[1]))b[1]=0},setEaseValue:function(a,b){if(b[4]){var c=(this._currentTime-this._startTime)*2/this._durationTime;this.setValue(this.ease(c>
1?2-c:c,b[1],b[0]-b[1],1),a,b)}else this.setValue(this.ease(this._currentTime-this._startTime<0?0:this._currentTime-this._startTime,b[1],b[0]-b[1],this._durationTime),a,b)},setValue:function(a,b,c){if(!isNaN(a)){a=this.plugin[b]?this.plugin[b].setOutput(a):a;this._appliedTarget[b]=c.length>2?(c[2]?c[2]:"")+a+(c[3]?c[3]:""):a}},kill:function(){cancelAnimationFrame(this.onLoop);this.isFinished=true},pause:function(){if(this._pauseTime==0)this._pauseTime=(new Date).getTime();this._isPaused=true},resume:function(){if(this._pauseTime>
0){var a=(new Date).getTime()-this._pauseTime;this._currentTime+=a;this._startTime+=a;_pauseTime=(new Date).getTime();this._pauseTime=0}if(this._isPaused)this._isPaused=false},removeProperties:function(a){if(a){var b=0;for(propertyName in this.properties)if(propertyName in a)delete this.properties[propertyName];else b++;return b}else for(propertyName in this.properties)delete this.properties[propertyName];return 0},changeFrom:function(a,b){if(this._isHTML)a=getPropertyName(a);this.setProperty(a,this.properties[a]);
if(this.properties[a])if(this.plugin[a])this.plugin[a].setFrom(b);else this.properties[a][1]=b},changeTo:function(a,b){if(this._isHTML)a=getPropertyName(a);if(this.properties[a])if(this.plugin[a])this.plugin[a].setTo(b);else this.properties[a][0]=b},getCurrentPropertyValue:function(a){var b=/[A-Z]/g;if(a.search(b)>-1){a=a.replace(b,function(c){return"-"+c.toLowerCase()});if(a.indexOf("ms")==0)a="-"+a}return window.getComputedStyle(this._target,"null").getPropertyValue(a)}};
var EKTweenFunc={linear:function(a,b,c,d){return c*a/d+b},easeInQuad:function(a,b,c,d){return c*(a/=d)*a+b},easeOutQuad:function(a,b,c,d){return-c*(a/=d)*(a-2)+b},easeInOutQuad:function(a,b,c,d){if((a/=d/2)<1)return c/2*a*a+b;return-c/2*(--a*(a-2)-1)+b},easeInCubic:function(a,b,c,d){return c*(a/=d)*a*a+b},easeOutCubic:function(a,b,c,d){return c*((a=a/d-1)*a*a+1)+b},easeInOutCubic:function(a,b,c,d){if((a/=d/2)<1)return c/2*a*a*a+b;return c/2*((a-=2)*a*a+2)+b},easeOutInCubic:function(a,b,c,d){if(a<
d/2)return EKTweenFunc.easeOutCubic(a*2,b,c/2,d);return EKTweenFunc.easeInCubic(a*2-d,b+c/2,c/2,d)},easeInQuart:function(a,b,c,d){return c*(a/=d)*a*a*a+b},easeOutQuart:function(a,b,c,d){return-c*((a=a/d-1)*a*a*a-1)+b},easeInOutQuart:function(a,b,c,d){if((a/=d/2)<1)return c/2*a*a*a*a+b;return-c/2*((a-=2)*a*a*a-2)+b},easeOutInQuart:function(a,b,c,d){if(a<d/2)return EKTweenFunc.easeOutQuart(a*2,b,c/2,d);return EKTweenFunc.easeInQuart(a*2-d,b+c/2,c/2,d)},easeInQuint:function(a,b,c,d){return c*(a/=d)*
a*a*a*a+b},easeOutQuint:function(a,b,c,d){return c*((a=a/d-1)*a*a*a*a+1)+b},easeInOutQuint:function(a,b,c,d){if((a/=d/2)<1)return c/2*a*a*a*a*a+b;return c/2*((a-=2)*a*a*a*a+2)+b},easeOutInQuint:function(a,b,c,d){if(a<d/2)return EKTweenFunc.easeOutQuint(a*2,b,c/2,d);return EKTweenFunc.easeInQuint(a*2-d,b+c/2,c/2,d)},easeInSine:function(a,b,c,d){return-c*Math.cos(a/d*(Math.PI/2))+c+b},easeOutSine:function(a,b,c,d){return c*Math.sin(a/d*(Math.PI/2))+b},easeInOutSine:function(a,b,c,d){return-c/2*(Math.cos(Math.PI*
a/d)-1)+b},easeOutInSine:function(a,b,c,d){if(a<d/2)return EKTweenFunc.easeOutSine(a*2,b,c/2,d);return EKTweenFunc.easeInSine(a*2-d,b+c/2,c/2,d)},easeInExpo:function(a,b,c,d){return a==0?b:c*Math.pow(2,10*(a/d-1))+b-c*0.001},easeOutExpo:function(a,b,c,d){return a==d?b+c:c*1.001*(-Math.pow(2,-10*a/d)+1)+b},easeInOutExpo:function(a,b,c,d){if(a==0)return b;if(a==d)return b+c;if((a/=d/2)<1)return c/2*Math.pow(2,10*(a-1))+b-c*5.0E-4;return c/2*1.0005*(-Math.pow(2,-10*--a)+2)+b},easeOutInExpo:function(a,
b,c,d){if(a<d/2)return EKTweenFunc.easeOutExpo(a*2,b,c/2,d);return EKTweenFunc.easeInExpo(a*2-d,b+c/2,c/2,d)},easeInCirc:function(a,b,c,d){return-c*(Math.sqrt(1-(a/=d)*a)-1)+b},easeOutCirc:function(a,b,c,d){return c*Math.sqrt(1-(a=a/d-1)*a)+b},easeInOutCirc:function(a,b,c,d){if((a/=d/2)<1)return-c/2*(Math.sqrt(1-a*a)-1)+b;return c/2*(Math.sqrt(1-(a-=2)*a)+1)+b},easeOutInCirc:function(a,b,c,d){if(a<d/2)return EKTweenFunc.easeOutCirc(a*2,b,c/2,d);return EKTweenFunc.easeInCirc(a*2-d,b+c/2,c/2,d)},easeInElastic:function(a,
b,c,d,e,g){if(a==0)return b;if((a/=d)==1)return b+c;g||(g=d*0.3);if(!e||e<Math.abs(c)){e=c;c=g/4}else c=g/(2*Math.PI)*Math.asin(c/e);return-(e*Math.pow(2,10*(a-=1))*Math.sin((a*d-c)*2*Math.PI/g))+b},easeOutElastic:function(a,b,c,d,e,g){var j;if(a==0)return b;if((a/=d)==1)return b+c;g||(g=d*0.3);if(!e||e<Math.abs(c)){e=c;j=g/4}else j=g/(2*Math.PI)*Math.asin(c/e);return e*Math.pow(2,-10*a)*Math.sin((a*d-j)*2*Math.PI/g)+c+b},easeInOutElastic:function(a,b,c,d,e,g){var j;if(a==0)return b;if((a/=d/2)==
2)return b+c;g||(g=d*0.3*1.5);if(!e||e<Math.abs(c)){e=c;j=g/4}else j=g/(2*Math.PI)*Math.asin(c/e);if(a<1)return-0.5*e*Math.pow(2,10*(a-=1))*Math.sin((a*d-j)*2*Math.PI/g)+b;return e*Math.pow(2,-10*(a-=1))*Math.sin((a*d-j)*2*Math.PI/g)*0.5+c+b},easeOutInElastic:function(a,b,c,d,e,g){if(a<d/2)return EKTweenFunc.easeOutElastic(a*2,b,c/2,d,e,g);return EKTweenFunc.easeInElastic(a*2-d,b+c/2,c/2,d,e,g)},easeInBack:function(a,b,c,d,e){if(e==undefined)e=1.70158;return c*(a/=d)*a*((e+1)*a-e)+b},easeOutBack:function(a,
b,c,d,e){if(e==undefined)e=1.70158;return c*((a=a/d-1)*a*((e+1)*a+e)+1)+b},easeInOutBack:function(a,b,c,d,e){if(e==undefined)e=1.70158;if((a/=d/2)<1)return c/2*a*a*(((e*=1.525)+1)*a-e)+b;return c/2*((a-=2)*a*(((e*=1.525)+1)*a+e)+2)+b},easeOutInBack:function(a,b,c,d,e){if(a<d/2)return EKTweenFunc.easeOutBack(a*2,b,c/2,d,e);return EKTweenFunc.easeInBack(a*2-d,b+c/2,c/2,d,e)},easeInBounce:function(a,b,c,d){return c-EKTweenFunc.easeOutBounce(d-a,0,c,d)+b},easeOutBounce:function(a,b,c,d){return(a/=d)<
1/2.75?c*7.5625*a*a+b:a<2/2.75?c*(7.5625*(a-=1.5/2.75)*a+0.75)+b:a<2.5/2.75?c*(7.5625*(a-=2.25/2.75)*a+0.9375)+b:c*(7.5625*(a-=2.625/2.75)*a+0.984375)+b},easeInOutBounce:function(a,b,c,d){return a<d/2?EKTweenFunc.easeInBounce(a*2,0,c,d)*0.5+b:EKTweenFunc.easeOutBounce(a*2-d,0,c,d)*0.5+c*0.5+b},easeOutInBounce:function(a,b,c,d){if(a<d/2)return EKTweenFunc.easeOutBounce(a*2,b,c/2,d);return EKTweenFunc.easeInBounce(a*2-d,b+c/2,c/2,d)}};EKTweenFunc.defaultFunc=EKTweenFunc.easeOutCirc;function EKTweenerColorPlugin(){var a=[0,0,0],b=[0,0,0];this.setFrom=function(e){d(a,e)};this.setTo=function(e){d(b,e)};this.setOutput=function(e){return"#"+c(a[0],b[0],e)+c(a[1],b[1],e)+c(a[2],b[2],e)};var c=function(e,g,j){e=(e+(g-e)*j>>0).toString(16);if(e.length==0)e="00";if(e.length==1)e="0"+e;return e},d=function(e,g){if(g.substr(0,1)=="#")if(g.length==4){e[0]=parseInt(g.substr(1,1),16)*17;e[1]=parseInt(g.substr(2,1),16)*17;e[2]=parseInt(g.substr(3,1),16)*17}else{if(g.length==7){e[0]=parseInt(g.substr(1,
2),16);e[1]=parseInt(g.substr(3,2),16);e[2]=parseInt(g.substr(5,2),16)}}else{g=/(.*?)rgb\((\d+), (\d+), (\d+)\)/.exec(g);e[0]=parseInt(g[2]);e[1]=parseInt(g[3]);e[2]=parseInt(g[4])}}}if(EKTweener)EKTweener.HTMLPlugins.backgroundColor=EKTweener.HTMLPlugins.color=EKTweenerColorPlugin;function EKTweenerOpacityPlugin(){var a,b;this.setFrom=function(c){if(c)if(typeof c=="number")a=parseFloat(c);else{var d=c.indexOf("alpha");a=d>-1?parseFloat(c.slice(c.indexOf("=",d)+1))/100:1}else a=1};this.setTo=function(c){b=c};this.setOutput=function(c){return"alpha(opacity="+(a+(b-a)*c)*100+")"}}EKTweenerOpacityPlugin.hasOpacity=function(){return"opacity"in document.createElement("div").style}();
if(EKTweener)if(!EKTweenerOpacityPlugin.hasOpacity){EKTweener.HTMLStyleAlias.opacity="filter";EKTweener.HTMLPlugins.opacity=EKTweenerOpacityPlugin};function EKTweenerTransform3dPlugin(){var a=[0,0,0,0,0,0,0,0,0,0,0,0],b=[0,0,0,0,0,0,0,0,0,0,0,0];this.setFrom=function(d){c(a,d)};this.setTo=function(d){c(b,d)};this.setOutput=function(d){return"matrix3d("+(a[0]+(b[0]-a[0])*d)+","+(a[1]+(b[1]-a[1])*d)+","+(a[2]+(b[2]-a[2])*d)+",0,"+(a[3]+(b[3]-a[3])*d)+","+(a[4]+(b[4]-a[4])*d)+","+(a[5]+(b[5]-a[5])*d)+",0,"+(a[6]+(b[6]-a[6])*d)+","+(a[7]+(b[7]-a[7])*d)+","+(a[8]+(b[8]-a[8])*d)+",0,"+(a[9]+(b[9]-a[9])*d)+","+(a[10]+(b[10]-a[10])*d)+","+(a[11]+(b[11]-
a[11])*d)+",1)"};var c=function(d,e){e=EKTweener.getStyle("transform",e);if(e.indexOf("matrix3d")>-1){e=e.substring(9,e.length-1).split(",");for(var g=0,j=0;g<15;g++)if(!(g==3||g==7||g==11)){d[j]=parseFloat(e[g]);j++}}else if(e.indexOf("matrix")>-1){e=e.substring(7,e.length-1).split(",");d[0]=parseFloat(e[0]);d[1]=parseFloat(e[1]);d[2]=0;d[3]=parseFloat(e[2]);d[4]=parseFloat(e[3]);d[5]=0;d[6]=0;d[7]=0;d[8]=1;d[9]=parseFloat(e[4]);d[10]=parseFloat(e[5]);d[11]=0}else{d[0]=d[4]=d[8]=d[11]=1;d[1]=d[2]=
d[3]=d[5]=d[6]=d[7]=d[9]=d[10]=0}}}if(EKTweener){EKTweener.HTMLStyleAlias.transform3d="transform";EKTweener.HTMLPrefixedStyle.push("transform");EKTweener.HTMLPlugins.transform3d=EKTweenerTransform3dPlugin};